-- Databricks notebook source
CREATE WIDGET TEXT logicalenv DEFAULT "prd001";

-- COMMAND ----------

WITH EANL_V1
AS (
	SELECT EANL.*,
		salnk.HUB_NMI_HSH_KEY1
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.SALNK_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EANL sat
		) EANL
	INNER JOIN im${logicalenv}_rawvault.SALNK_NMI salnk
		ON EANL.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
			AND EANL.rec_seq = 1
			AND trim(EANL.NODISCONCT) = 'LS'
			AND EANL.CHANGE_TYPE <> 'D'
	),
EUIINSTLN_V2
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2
	FROM im${logicalenv}_rawvault.SALNK_NMI salnk
	INNER JOIN im${logicalenv}_rawvault.LSAT_NMI_CIS_EUIINSTLN sat
		ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
EUITRANS_V3
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2,
		hub.NMI
	FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EUITRANS sat
	INNER JOIN im${logicalenv}_rawvault.SALNK_NMI salnk
		ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	INNER JOIN im${logicalenv}_rawvault.HUB_NMI hub
		ON salnk.HUB_NMI_HSH_KEY1 = hub.HUB_NMI_HSH_KEY
	WHERE length(trim(sat.NMI_CHECKSUM)) > 0
		AND sat.CHANGE_TYPE <> 'D'
	),
ZIIDTT_NMI_STAT_V4
AS (
	SELECT *
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.HUB_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.SAT_NMI_CIS_ZIIDTT_NMI_STAT sat
		WHERE sat.TO_DT = '99991231'
			AND length(trim(sat.NMI_CHECKSUM)) > 0
		) a
	WHERE rec_seq = 1
    AND TRIM(a.NMI_STATUS) NOT IN ('X') 
	),
EASTL_V5
AS (
	SELECT lnk.HUB_NMI_HSH_KEY,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT lnk
	INNER JOIN im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT_CIS_EASTL sat
		ON sat.LNK_NMI_EQUIPMENT_HSH_KEY = lnk.LNK_NMI_EQUIPMENT_HSH_KEY
	WHERE sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EGERH_V6
AS (
	SELECT salnk.HUB_EQUIPMENT_HSH_KEY2,
		salnk.HUB_EQUIPMENT_HSH_KEY1
	FROM im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT2_CIS_EGERH sat
	INNER JOIN im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT2 salnk
		ON sat.LNK_NMI_EQUIPMENT2_HSH_KEY = salnk.LNK_NMI_EQUIPMENT2_HSH_KEY
	WHERE sat.KOMBINAT = 'Z'
		AND sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EQUI_V7
AS (
	SELECT hub.DEVICE_ID AS SERNR,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LSAT_EQUIPMENT_DEVICE_MATERIAL_CIS_EQUI sat
	INNER JOIN im${logicalenv}_rawvault.LNK_EQUIPMENT_DEVICE_MATERIAL lnk
		ON sat.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY = lnk.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY
	INNER JOIN im${logicalenv}_rawvault.HUB_DEVICE hub
		ON lnk.HUB_DEVICE_HSH_KEY = hub.HUB_DEVICE_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
LS as 
(SELECT DISTINCT EUITRANS_V3.NMI,
	EANL_V1.NODISCONCT AS LIFE_SUPPORT_FLAG,
	ZIIDTT_NMI_STAT_V4.NMI_STATUS,
	TRIM(EQUI_V7.SERNR) AS METER_NUM,
	date_format(from_utc_timestamp(current_timestamp(), 'GMT+10'), 'yyyy-MM-dd HH:mm:ss') AS ROW_INSERT_DTM
FROM EANL_V1
INNER JOIN EUIINSTLN_V2
	ON EANL_V1.HUB_NMI_HSH_KEY1 = EUIINSTLN_V2.HUB_NMI_HSH_KEY1
INNER JOIN EUITRANS_V3
	ON EUIINSTLN_V2.HUB_NMI_HSH_KEY2 = EUITRANS_V3.HUB_NMI_HSH_KEY2
INNER JOIN ZIIDTT_NMI_STAT_V4
	ON EUITRANS_V3.HUB_NMI_HSH_KEY1 = ZIIDTT_NMI_STAT_V4.HUB_NMI_HSH_KEY
LEFT JOIN EASTL_V5
	ON EANL_V1.HUB_NMI_HSH_KEY1 = EASTL_V5.HUB_NMI_HSH_KEY
INNER JOIN EGERH_V6
	ON EASTL_V5.HUB_EQUIPMENT_HSH_KEY = EGERH_V6.HUB_EQUIPMENT_HSH_KEY2
INNER JOIN EQUI_V7
	ON EGERH_V6.HUB_EQUIPMENT_HSH_KEY1 = EQUI_V7.HUB_EQUIPMENT_HSH_KEY)
    select count(*) from LS

-- COMMAND ----------

WITH EANL_V1
AS (
	SELECT EANL.*,
		salnk.HUB_NMI_HSH_KEY1
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.SALNK_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EANL sat
			-- WHERE date_format(sat.EXTRACT_DATE_TIME, "yyyyMMdd") < date_format('${run_date}', "yyyyMMdd")
		) EANL
	JOIN im${logicalenv}_rawvault.SALNK_NMI salnk ON EANL.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
		AND EANL.rec_seq = 1
		AND trim(EANL.NODISCONCT) = 'LS'
		AND EANL.CHANGE_TYPE <> 'D'
	),
EUIINSTLN_V2
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2
	FROM im${logicalenv}_rawvault.SALNK_NMI salnk
	JOIN im${logicalenv}_rawvault.LSAT_NMI_CIS_EUIINSTLN sat ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
EUITRANS_V3
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2,
		hub.NMI
	FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EUITRANS sat
	JOIN im${logicalenv}_rawvault.SALNK_NMI salnk ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	JOIN im${logicalenv}_rawvault.HUB_NMI hub ON salnk.HUB_NMI_HSH_KEY1 = hub.HUB_NMI_HSH_KEY
	WHERE length(trim(sat.NMI_CHECKSUM)) > 0
		AND sat.CHANGE_TYPE <> 'D'
	),
ZIIDTT_NMI_STAT_V4
AS (
	SELECT *
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.HUB_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.SAT_NMI_CIS_ZIIDTT_NMI_STAT sat
		WHERE TRIM(sat.NMI_STATUS) IN ('A', 'D', 'G')
			AND sat.TO_DT = '99991231'
			AND length(trim(sat.NMI_CHECKSUM)) > 0
		) a
	WHERE rec_seq = 1
	),
EASTL_V5
AS (
	SELECT lnk.HUB_NMI_HSH_KEY,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT lnk
	JOIN im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT_CIS_EASTL sat ON sat.LNK_NMI_EQUIPMENT_HSH_KEY = lnk.LNK_NMI_EQUIPMENT_HSH_KEY
	WHERE sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EGERH_V6
AS (
	SELECT salnk.HUB_EQUIPMENT_HSH_KEY2,
		salnk.HUB_EQUIPMENT_HSH_KEY1
	FROM im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT2_CIS_EGERH sat
	JOIN im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT2 salnk ON sat.LNK_NMI_EQUIPMENT2_HSH_KEY = salnk.LNK_NMI_EQUIPMENT2_HSH_KEY
	WHERE sat.KOMBINAT = 'Z'
		AND sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EQUI_V7
AS (
	SELECT hub.DEVICE_ID AS SERNR,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LSAT_EQUIPMENT_DEVICE_MATERIAL_CIS_EQUI sat
	JOIN im${logicalenv}_rawvault.LNK_EQUIPMENT_DEVICE_MATERIAL lnk ON sat.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY = lnk.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY
	JOIN im${logicalenv}_rawvault.HUB_DEVICE hub ON lnk.HUB_DEVICE_HSH_KEY = hub.HUB_DEVICE_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
LS as     
(SELECT DISTINCT EUITRANS_V3.NMI,
	EANL_V1.NODISCONCT AS LIFE_SUPPORT_FLAG,
	ZIIDTT_NMI_STAT_V4.NMI_STATUS,
	TRIM(EQUI_V7.SERNR) AS METER_NUM,
	date_format(from_utc_timestamp(current_timestamp(), 'GMT+10'), 'yyyy-MM-dd HH:mm:ss') AS ROW_INSERT_DTM
FROM EANL_V1
JOIN EUIINSTLN_V2 ON EANL_V1.HUB_NMI_HSH_KEY1 = EUIINSTLN_V2.HUB_NMI_HSH_KEY1
JOIN EUITRANS_V3 ON EUIINSTLN_V2.HUB_NMI_HSH_KEY2 = EUITRANS_V3.HUB_NMI_HSH_KEY2
JOIN ZIIDTT_NMI_STAT_V4 ON EUITRANS_V3.HUB_NMI_HSH_KEY1 = ZIIDTT_NMI_STAT_V4.HUB_NMI_HSH_KEY
LEFT OUTER JOIN EASTL_V5 ON EANL_V1.HUB_NMI_HSH_KEY1 = EASTL_V5.HUB_NMI_HSH_KEY
JOIN EGERH_V6 ON EASTL_V5.HUB_EQUIPMENT_HSH_KEY = EGERH_V6.HUB_EQUIPMENT_HSH_KEY2
JOIN EQUI_V7 ON EGERH_V6.HUB_EQUIPMENT_HSH_KEY1 = EQUI_V7.HUB_EQUIPMENT_HSH_KEY
) select count(9) from LS

-- COMMAND ----------

WITH EANL_V1
AS (
	SELECT EANL.*,
		salnk.HUB_NMI_HSH_KEY1
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.SALNK_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EANL sat
		) EANL
	INNER JOIN im${logicalenv}_rawvault.SALNK_NMI salnk
		ON EANL.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
			AND EANL.rec_seq = 1
			AND trim(EANL.NODISCONCT) = 'LS'
			AND EANL.CHANGE_TYPE <> 'D'
	),
EUIINSTLN_V2
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2
	FROM im${logicalenv}_rawvault.SALNK_NMI salnk
	INNER JOIN im${logicalenv}_rawvault.LSAT_NMI_CIS_EUIINSTLN sat
		ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
EUITRANS_V3
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2,
		hub.NMI
	FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EUITRANS sat
	INNER JOIN im${logicalenv}_rawvault.SALNK_NMI salnk
		ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	INNER JOIN im${logicalenv}_rawvault.HUB_NMI hub
		ON salnk.HUB_NMI_HSH_KEY1 = hub.HUB_NMI_HSH_KEY
	WHERE length(trim(sat.NMI_CHECKSUM)) > 0
		AND sat.CHANGE_TYPE <> 'D'
	),
ZIIDTT_NMI_STAT_V4
AS (
	SELECT *
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.HUB_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.SAT_NMI_CIS_ZIIDTT_NMI_STAT sat
		WHERE sat.TO_DT = '99991231'
			AND length(trim(sat.NMI_CHECKSUM)) > 0
		) a
	WHERE rec_seq = 1
    AND TRIM(a.NMI_STATUS) NOT IN ('X') 
	),
EASTL_V5
AS (
	SELECT lnk.HUB_NMI_HSH_KEY,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT lnk
	INNER JOIN im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT_CIS_EASTL sat
		ON sat.LNK_NMI_EQUIPMENT_HSH_KEY = lnk.LNK_NMI_EQUIPMENT_HSH_KEY
	WHERE sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EGERH_V6
AS (
	SELECT salnk.HUB_EQUIPMENT_HSH_KEY2,
		salnk.HUB_EQUIPMENT_HSH_KEY1
	FROM im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT2_CIS_EGERH sat
	INNER JOIN im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT2 salnk
		ON sat.LNK_NMI_EQUIPMENT2_HSH_KEY = salnk.LNK_NMI_EQUIPMENT2_HSH_KEY
	WHERE sat.KOMBINAT = 'Z'
		AND sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EQUI_V7
AS (
	SELECT hub.DEVICE_ID AS SERNR,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LSAT_EQUIPMENT_DEVICE_MATERIAL_CIS_EQUI sat
	INNER JOIN im${logicalenv}_rawvault.LNK_EQUIPMENT_DEVICE_MATERIAL lnk
		ON sat.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY = lnk.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY
	INNER JOIN im${logicalenv}_rawvault.HUB_DEVICE hub
		ON lnk.HUB_DEVICE_HSH_KEY = hub.HUB_DEVICE_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
LS as 
(SELECT DISTINCT EUITRANS_V3.NMI,
	EANL_V1.NODISCONCT AS LIFE_SUPPORT_FLAG,
	ZIIDTT_NMI_STAT_V4.NMI_STATUS,
	TRIM(EQUI_V7.SERNR) AS METER_NUM,
	date_format(from_utc_timestamp(current_timestamp(), 'GMT+10'), 'yyyy-MM-dd HH:mm:ss') AS ROW_INSERT_DTM
FROM EANL_V1
INNER JOIN EUIINSTLN_V2
	ON EANL_V1.HUB_NMI_HSH_KEY1 = EUIINSTLN_V2.HUB_NMI_HSH_KEY1
INNER JOIN EUITRANS_V3
	ON EUIINSTLN_V2.HUB_NMI_HSH_KEY2 = EUITRANS_V3.HUB_NMI_HSH_KEY2
INNER JOIN ZIIDTT_NMI_STAT_V4
	ON EUITRANS_V3.HUB_NMI_HSH_KEY1 = ZIIDTT_NMI_STAT_V4.HUB_NMI_HSH_KEY
LEFT JOIN EASTL_V5
	ON EANL_V1.HUB_NMI_HSH_KEY1 = EASTL_V5.HUB_NMI_HSH_KEY
INNER JOIN EGERH_V6
	ON EASTL_V5.HUB_EQUIPMENT_HSH_KEY = EGERH_V6.HUB_EQUIPMENT_HSH_KEY2
INNER JOIN EQUI_V7
	ON EGERH_V6.HUB_EQUIPMENT_HSH_KEY1 = EQUI_V7.HUB_EQUIPMENT_HSH_KEY)
    select count(*) from LS

-- COMMAND ----------

WITH EANL_V1
AS (
	SELECT EANL.*,
		salnk.HUB_NMI_HSH_KEY1
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.SALNK_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EANL sat
			-- WHERE date_format(sat.EXTRACT_DATE_TIME, "yyyyMMdd") < date_format('${run_date}', "yyyyMMdd")
		) EANL
	JOIN im${logicalenv}_rawvault.SALNK_NMI salnk ON EANL.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
		AND EANL.rec_seq = 1
		AND trim(EANL.NODISCONCT) = 'LS'
		AND EANL.CHANGE_TYPE <> 'D'
	),
EUIINSTLN_V2
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2
	FROM im${logicalenv}_rawvault.SALNK_NMI salnk
	JOIN im${logicalenv}_rawvault.LSAT_NMI_CIS_EUIINSTLN sat ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
EUITRANS_V3
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2,
		hub.NMI
	FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EUITRANS sat
	JOIN im${logicalenv}_rawvault.SALNK_NMI salnk ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	JOIN im${logicalenv}_rawvault.HUB_NMI hub ON salnk.HUB_NMI_HSH_KEY1 = hub.HUB_NMI_HSH_KEY
	WHERE length(trim(sat.NMI_CHECKSUM)) > 0
		AND sat.CHANGE_TYPE <> 'D'
	),
ZIIDTT_NMI_STAT_V4
AS (
	SELECT *
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.HUB_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.SAT_NMI_CIS_ZIIDTT_NMI_STAT sat
		WHERE TRIM(sat.NMI_STATUS) IN ('A', 'D', 'G')
			AND sat.TO_DT = '99991231'
			AND length(trim(sat.NMI_CHECKSUM)) > 0
		) a
	WHERE rec_seq = 1
	),
EASTL_V5
AS (
	SELECT lnk.HUB_NMI_HSH_KEY,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT lnk
	JOIN im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT_CIS_EASTL sat ON sat.LNK_NMI_EQUIPMENT_HSH_KEY = lnk.LNK_NMI_EQUIPMENT_HSH_KEY
	WHERE sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EGERH_V6
AS (
	SELECT salnk.HUB_EQUIPMENT_HSH_KEY2,
		salnk.HUB_EQUIPMENT_HSH_KEY1
	FROM im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT2_CIS_EGERH sat
	JOIN im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT2 salnk ON sat.LNK_NMI_EQUIPMENT2_HSH_KEY = salnk.LNK_NMI_EQUIPMENT2_HSH_KEY
	WHERE sat.KOMBINAT = 'Z'
		AND sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EQUI_V7
AS (
	SELECT hub.DEVICE_ID AS SERNR,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LSAT_EQUIPMENT_DEVICE_MATERIAL_CIS_EQUI sat
	JOIN im${logicalenv}_rawvault.LNK_EQUIPMENT_DEVICE_MATERIAL lnk ON sat.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY = lnk.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY
	JOIN im${logicalenv}_rawvault.HUB_DEVICE hub ON lnk.HUB_DEVICE_HSH_KEY = hub.HUB_DEVICE_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
LS as     
(SELECT DISTINCT EUITRANS_V3.NMI,
	EANL_V1.NODISCONCT AS LIFE_SUPPORT_FLAG,
	ZIIDTT_NMI_STAT_V4.NMI_STATUS,
	TRIM(EQUI_V7.SERNR) AS METER_NUM,
	date_format(from_utc_timestamp(current_timestamp(), 'GMT+10'), 'yyyy-MM-dd HH:mm:ss') AS ROW_INSERT_DTM
FROM EANL_V1
JOIN EUIINSTLN_V2 ON EANL_V1.HUB_NMI_HSH_KEY1 = EUIINSTLN_V2.HUB_NMI_HSH_KEY1
JOIN EUITRANS_V3 ON EUIINSTLN_V2.HUB_NMI_HSH_KEY2 = EUITRANS_V3.HUB_NMI_HSH_KEY2
JOIN ZIIDTT_NMI_STAT_V4 ON EUITRANS_V3.HUB_NMI_HSH_KEY1 = ZIIDTT_NMI_STAT_V4.HUB_NMI_HSH_KEY
LEFT OUTER JOIN EASTL_V5 ON EANL_V1.HUB_NMI_HSH_KEY1 = EASTL_V5.HUB_NMI_HSH_KEY
JOIN EGERH_V6 ON EASTL_V5.HUB_EQUIPMENT_HSH_KEY = EGERH_V6.HUB_EQUIPMENT_HSH_KEY2
JOIN EQUI_V7 ON EGERH_V6.HUB_EQUIPMENT_HSH_KEY1 = EQUI_V7.HUB_EQUIPMENT_HSH_KEY
) select count(9) from LS

-- COMMAND ----------

WITH EANL_V1
AS (
	SELECT EANL.*,
		salnk.HUB_NMI_HSH_KEY1
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.SALNK_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EANL sat
		) EANL
	INNER JOIN im${logicalenv}_rawvault.SALNK_NMI salnk
		ON EANL.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
			AND EANL.rec_seq = 1
			AND trim(EANL.NODISCONCT) = 'LS'
			AND EANL.CHANGE_TYPE <> 'D'
	),
EUIINSTLN_V2
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2
	FROM im${logicalenv}_rawvault.SALNK_NMI salnk
	INNER JOIN im${logicalenv}_rawvault.LSAT_NMI_CIS_EUIINSTLN sat
		ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
EUITRANS_V3
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2,
		hub.NMI
	FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EUITRANS sat
	INNER JOIN im${logicalenv}_rawvault.SALNK_NMI salnk
		ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	INNER JOIN im${logicalenv}_rawvault.HUB_NMI hub
		ON salnk.HUB_NMI_HSH_KEY1 = hub.HUB_NMI_HSH_KEY
	WHERE length(trim(sat.NMI_CHECKSUM)) > 0
		AND sat.CHANGE_TYPE <> 'D'
	),
ZIIDTT_NMI_STAT_V4
AS (
	SELECT *
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.HUB_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.SAT_NMI_CIS_ZIIDTT_NMI_STAT sat
		WHERE sat.TO_DT = '99991231'
			AND length(trim(sat.NMI_CHECKSUM)) > 0
		) a
	WHERE rec_seq = 1
    AND TRIM(a.NMI_STATUS) NOT IN ('X') 
	),
EASTL_V5
AS (
	SELECT lnk.HUB_NMI_HSH_KEY,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT lnk
	INNER JOIN im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT_CIS_EASTL sat
		ON sat.LNK_NMI_EQUIPMENT_HSH_KEY = lnk.LNK_NMI_EQUIPMENT_HSH_KEY
	WHERE sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EGERH_V6
AS (
	SELECT salnk.HUB_EQUIPMENT_HSH_KEY2,
		salnk.HUB_EQUIPMENT_HSH_KEY1
	FROM im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT2_CIS_EGERH sat
	INNER JOIN im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT2 salnk
		ON sat.LNK_NMI_EQUIPMENT2_HSH_KEY = salnk.LNK_NMI_EQUIPMENT2_HSH_KEY
	WHERE sat.KOMBINAT = 'Z'
		AND sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EQUI_V7
AS (
	SELECT hub.DEVICE_ID AS SERNR,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LSAT_EQUIPMENT_DEVICE_MATERIAL_CIS_EQUI sat
	INNER JOIN im${logicalenv}_rawvault.LNK_EQUIPMENT_DEVICE_MATERIAL lnk
		ON sat.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY = lnk.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY
	INNER JOIN im${logicalenv}_rawvault.HUB_DEVICE hub
		ON lnk.HUB_DEVICE_HSH_KEY = hub.HUB_DEVICE_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
LS as 
(SELECT DISTINCT EUITRANS_V3.NMI,
	EANL_V1.NODISCONCT AS LIFE_SUPPORT_FLAG,
	ZIIDTT_NMI_STAT_V4.NMI_STATUS,
	TRIM(EQUI_V7.SERNR) AS METER_NUM,
	date_format(from_utc_timestamp(current_timestamp(), 'GMT+10'), 'yyyy-MM-dd HH:mm:ss') AS ROW_INSERT_DTM
FROM EANL_V1
INNER JOIN EUIINSTLN_V2
	ON EANL_V1.HUB_NMI_HSH_KEY1 = EUIINSTLN_V2.HUB_NMI_HSH_KEY1
INNER JOIN EUITRANS_V3
	ON EUIINSTLN_V2.HUB_NMI_HSH_KEY2 = EUITRANS_V3.HUB_NMI_HSH_KEY2
INNER JOIN ZIIDTT_NMI_STAT_V4
	ON EUITRANS_V3.HUB_NMI_HSH_KEY1 = ZIIDTT_NMI_STAT_V4.HUB_NMI_HSH_KEY
LEFT JOIN EASTL_V5
	ON EANL_V1.HUB_NMI_HSH_KEY1 = EASTL_V5.HUB_NMI_HSH_KEY
INNER JOIN EGERH_V6
	ON EASTL_V5.HUB_EQUIPMENT_HSH_KEY = EGERH_V6.HUB_EQUIPMENT_HSH_KEY2
INNER JOIN EQUI_V7
	ON EGERH_V6.HUB_EQUIPMENT_HSH_KEY1 = EQUI_V7.HUB_EQUIPMENT_HSH_KEY)
    select count(*) from LS

-- COMMAND ----------

WITH EANL_V1
AS (
	SELECT EANL.*,
		salnk.HUB_NMI_HSH_KEY1
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.SALNK_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EANL sat
			-- WHERE date_format(sat.EXTRACT_DATE_TIME, "yyyyMMdd") < date_format('${run_date}', "yyyyMMdd")
		) EANL
	JOIN im${logicalenv}_rawvault.SALNK_NMI salnk ON EANL.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
		AND EANL.rec_seq = 1
		AND trim(EANL.NODISCONCT) = 'LS'
		AND EANL.CHANGE_TYPE <> 'D'
	),
EUIINSTLN_V2
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2
	FROM im${logicalenv}_rawvault.SALNK_NMI salnk
	JOIN im${logicalenv}_rawvault.LSAT_NMI_CIS_EUIINSTLN sat ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
EUITRANS_V3
AS (
	SELECT salnk.HUB_NMI_HSH_KEY1,
		salnk.HUB_NMI_HSH_KEY2,
		hub.NMI
	FROM im${logicalenv}_rawvault.LSAT_NMI_CIS_EUITRANS sat
	JOIN im${logicalenv}_rawvault.SALNK_NMI salnk ON sat.SALNK_NMI_HSH_KEY = salnk.SALNK_NMI_HSH_KEY
	JOIN im${logicalenv}_rawvault.HUB_NMI hub ON salnk.HUB_NMI_HSH_KEY1 = hub.HUB_NMI_HSH_KEY
	WHERE length(trim(sat.NMI_CHECKSUM)) > 0
		AND sat.CHANGE_TYPE <> 'D'
	),
ZIIDTT_NMI_STAT_V4
AS (
	SELECT *
	FROM (
		SELECT sat.*,
			ROW_NUMBER() OVER (
				PARTITION BY sat.HUB_NMI_HSH_KEY ORDER BY sat.extract_date_time DESC
				) AS `rec_seq`
		FROM im${logicalenv}_rawvault.SAT_NMI_CIS_ZIIDTT_NMI_STAT sat
		WHERE sat.TO_DT = '99991231'
			AND length(trim(sat.NMI_CHECKSUM)) > 0
		) a
	WHERE rec_seq = 1
    AND TRIM(NMI_STATUS) IN ('A', 'D', 'G')
	),
EASTL_V5
AS (
	SELECT lnk.HUB_NMI_HSH_KEY,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT lnk
	JOIN im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT_CIS_EASTL sat ON sat.LNK_NMI_EQUIPMENT_HSH_KEY = lnk.LNK_NMI_EQUIPMENT_HSH_KEY
	WHERE sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EGERH_V6
AS (
	SELECT salnk.HUB_EQUIPMENT_HSH_KEY2,
		salnk.HUB_EQUIPMENT_HSH_KEY1
	FROM im${logicalenv}_rawvault.LSAT_NMI_EQUIPMENT2_CIS_EGERH sat
	JOIN im${logicalenv}_rawvault.LNK_NMI_EQUIPMENT2 salnk ON sat.LNK_NMI_EQUIPMENT2_HSH_KEY = salnk.LNK_NMI_EQUIPMENT2_HSH_KEY
	WHERE sat.KOMBINAT = 'Z'
		AND sat.BIS = '99991231'
		AND sat.CHANGE_TYPE <> 'D'
	),
EQUI_V7
AS (
	SELECT hub.DEVICE_ID AS SERNR,
		lnk.HUB_EQUIPMENT_HSH_KEY
	FROM im${logicalenv}_rawvault.LSAT_EQUIPMENT_DEVICE_MATERIAL_CIS_EQUI sat
	JOIN im${logicalenv}_rawvault.LNK_EQUIPMENT_DEVICE_MATERIAL lnk ON sat.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY = lnk.LNK_EQUIPMENT_DEVICE_MATERIAL_HSH_KEY
	JOIN im${logicalenv}_rawvault.HUB_DEVICE hub ON lnk.HUB_DEVICE_HSH_KEY = hub.HUB_DEVICE_HSH_KEY
	WHERE sat.CHANGE_TYPE <> 'D'
	),
LS as     
(SELECT DISTINCT EUITRANS_V3.NMI,
	EANL_V1.NODISCONCT AS LIFE_SUPPORT_FLAG,
	ZIIDTT_NMI_STAT_V4.NMI_STATUS,
	TRIM(EQUI_V7.SERNR) AS METER_NUM,
	date_format(from_utc_timestamp(current_timestamp(), 'GMT+10'), 'yyyy-MM-dd HH:mm:ss') AS ROW_INSERT_DTM
FROM EANL_V1
JOIN EUIINSTLN_V2 ON EANL_V1.HUB_NMI_HSH_KEY1 = EUIINSTLN_V2.HUB_NMI_HSH_KEY1
JOIN EUITRANS_V3 ON EUIINSTLN_V2.HUB_NMI_HSH_KEY2 = EUITRANS_V3.HUB_NMI_HSH_KEY2
JOIN ZIIDTT_NMI_STAT_V4 ON EUITRANS_V3.HUB_NMI_HSH_KEY1 = ZIIDTT_NMI_STAT_V4.HUB_NMI_HSH_KEY
LEFT OUTER JOIN EASTL_V5 ON EANL_V1.HUB_NMI_HSH_KEY1 = EASTL_V5.HUB_NMI_HSH_KEY
JOIN EGERH_V6 ON EASTL_V5.HUB_EQUIPMENT_HSH_KEY = EGERH_V6.HUB_EQUIPMENT_HSH_KEY2
JOIN EQUI_V7 ON EGERH_V6.HUB_EQUIPMENT_HSH_KEY1 = EQUI_V7.HUB_EQUIPMENT_HSH_KEY
) select count(9) from LS
