# Databricks notebook source
tab = ["imprd001_rawvault.HUB_ADDRESS",
"imprd001_rawvault.HUB_BILLING",
"imprd001_rawvault.HUB_BPEM",
"imprd001_rawvault.HUB_BUSINESS_PARTNER",
"imprd001_rawvault.HUB_DEVICE",
"imprd001_rawvault.HUB_DISCONNECTION",
"imprd001_rawvault.HUB_DOC",
"imprd001_rawvault.HUB_EQUIPMENT",
"imprd001_rawvault.HUB_GENERIC_OBJECT",
"imprd001_rawvault.HUB_MATERIAL",
"imprd001_rawvault.HUB_MEASURING_POINT",
"imprd001_rawvault.HUB_MRU",
"imprd001_rawvault.HUB_MTRREAD",
"imprd001_rawvault.HUB_NMI",
"imprd001_rawvault.HUB_NOTIFICATION",
"imprd001_rawvault.HUB_PARTICIPANT",
"imprd001_rawvault.HUB_PURCHASE",
"imprd001_rawvault.HUB_REF_ADRCITY",
"imprd001_rawvault.HUB_REF_ADRSTRTMRU",
"imprd001_rawvault.HUB_REF_CALENDAR",
"imprd001_rawvault.HUB_REF_CROSSREF",
"imprd001_rawvault.HUB_REF_DISCON_TYPE",
"imprd001_rawvault.HUB_REF_DOMAIN",
"imprd001_rawvault.HUB_REF_EIDESWTACTIVITYT",
"imprd001_rawvault.HUB_REF_EIDESWTSTATUST",
"imprd001_rawvault.HUB_REF_EIDESWTTYPEST",
"imprd001_rawvault.HUB_REF_ESTAT",
"imprd001_rawvault.HUB_REF_GRID_ALLOC",
"imprd001_rawvault.HUB_REF_IDOC_STRUCT",
"imprd001_rawvault.HUB_REF_ISTAT",
"imprd001_rawvault.HUB_REF_METER_CONFIG_INTERVAL",
"imprd001_rawvault.HUB_REF_MTR_CONFIG",
"imprd001_rawvault.HUB_REF_NCUL_ORM",
"imprd001_rawvault.HUB_REF_ORDER_TYP",
"imprd001_rawvault.HUB_REF_POSTCODE",
"imprd001_rawvault.HUB_REF_PUBLT_ORM",
"imprd001_rawvault.HUB_REF_RATE_CAT",
"imprd001_rawvault.HUB_REF_REGISTER_GRP",
"imprd001_rawvault.HUB_REF_STREET",
"imprd001_rawvault.HUB_REF_SUBSTATION",
"imprd001_rawvault.HUB_REF_WINDING_GRP",
"imprd001_rawvault.HUB_REF_WORKCENTER",
"imprd001_rawvault.HUB_REF_ZWORKCENTRE",
"imprd001_rawvault.HUB_SRVORDER",
"imprd001_rawvault.HUB_SUBSTATION",
"imprd001_rawvault.HUB_SWITCHDOC",
"imprd001_rawvault.HUB_SWITCHSTEP",
"imprd001_rawvault.HUB_WORKITEM"]
for x in tab:
  x = "OPTIMIZE " + x
  print(x)
  sqlContext.sql(x)

# COMMAND ----------

tab = ["imprd001_rawvault.LNK_BUSINESS_PARTNER_ADDRESS",
"imprd001_rawvault.LNK_DEVICE_EQUIPMENT",
"imprd001_rawvault.LNK_DEVICE_EQUIPMENT2",
"imprd001_rawvault.LNK_DISCONNECTION_NMI_EQUIPMENT",
"imprd001_rawvault.LNK_EQUIPMENT_DEVICE_MATERIAL",
"imprd001_rawvault.LNK_EQUIPMENT_MATERIAL",
"imprd001_rawvault.LNK_EQUIPMENT_MEASURING_POINT",
"imprd001_rawvault.LNK_EQUIPMENT_MTRREAD_DEVICE",
"imprd001_rawvault.LNK_NMI_ADDRESS",
"imprd001_rawvault.LNK_NMI_BILLING_BUSINESS_PARTNER",
"imprd001_rawvault.LNK_NMI_BUSINESS_PARTNER",
"imprd001_rawvault.LNK_NMI_DEVICE",
"imprd001_rawvault.LNK_NMI_DEVICE_BILLING",
"imprd001_rawvault.LNK_NMI_EQUIPMENT",
"imprd001_rawvault.LNK_NMI_EQUIPMENT_DEVICE_SRVORDER_MR",
"imprd001_rawvault.LNK_NMI_EQUIPMENT2",
"imprd001_rawvault.LNK_NMI_MTRREAD",
"imprd001_rawvault.LNK_NMI_PARTICIPANT",
"imprd001_rawvault.LNK_NMI_SWITCHDOC",
"imprd001_rawvault.LNK_PURCHASE_MATERIAL",
"imprd001_rawvault.LNK_SRVORDER_BUSINESS_PARTNER_ADDRESS",
"imprd001_rawvault.LNK_SRVORDER_MATERIAL_EQUIPMENT_DEVICE_NOTIFICATION",
"imprd001_rawvault.LNK_SWITCHDOC_SWITCHSTEP",
"imprd001_rawvault.LNK_SWITCHSTEP_DOC",
"imprd001_rawvault.SALNK_EQUIPMENT",
"imprd001_rawvault.SALNK_EQUIPMENT_COMMS",
"imprd001_rawvault.SALNK_EQUIPMENT_MATERIAL_DEVICE_MTRREAD_BILLING",
"imprd001_rawvault.SALNK_EQUIPMENT_REGISTER",
"imprd001_rawvault.SALNK_NMI",
"imprd001_rawvault.SALNK_NMI_SUBSTATION",
"imprd001_rawvault.SALNK_NMI2",
"imprd001_rawvault.SALNK_NOTIFICATION_DEVICE_MATERIAL_SRVORDER",
"imprd001_rawvault.SALNK_SRVORDER",
"imprd001_rawvault.SALNK_SRVORDER_MATERIAL",
"imprd001_rawvault.SALNK_SRVORDER_MATERIAL_EQUIPMENT_DEVICE_BUSINESS_PARTNER",
"imprd001_rawvault.SALNK_SRVORDER_SWITCHDOC_NMI",
"imprd001_rawvault.SALNK_NMI_BILLING"]
for x in tab:
  x = "OPTIMIZE " + x
  print(x)
  sqlContext.sql(x)
